In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt

In [2]:
df = pd.read_csv(r"E:\Great Learning\4. Python (Module-2)\project\USvideos.csv")

In [3]:
df2 = pd.read_json(r"E:\Great Learning\4. Python (Module-2)\project\US_category_id.json")

In [4]:
df.drop(['description','thumbnail_link','tags'],axis=1,inplace=True)

In [5]:
df['publish_time'] = pd.to_datetime(df['publish_time'])

In [6]:
df['trending_date'] = pd.to_datetime(df['trending_date'],format='%y.%d.%m')

In [7]:
df['publish_year'] = df['publish_time'].dt.year

In [8]:
df['publish_month'] = df['publish_time'].dt.month_name()

In [9]:
title = [df2['items'][i]['snippet']['title'] for i in range(0,32)]

In [10]:
id = [df2['items'][i]['id'] for i in range(0,32)]

In [11]:
id_genre = pd.DataFrame({'category_id':id,'genre':title})

In [12]:
id_genre['category_id'] = id_genre['category_id'].astype(int)

In [13]:
df = pd.merge(df,id_genre,how='inner',on='category_id')

In [14]:
df = df.loc[:,['video_id','publish_time','publish_year', 'publish_month', 'trending_date', 'title', 'channel_title', 'views', 'likes', 'dislikes', 'comment_count',
       'comments_disabled', 'ratings_disabled', 'video_error_or_removed','category_id', 'genre']]

In [15]:
df.head(3)

,video_id,publish_time,publish_year,publish_month,trending_date,title,channel_title,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,category_id,genre
0,2kyS6SvSYSE,2017-11-13 17:13:01+00:00,2017,November,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,748374,57527,2966,15954,False,False,False,22,People & Blogs
1,0mlNzVSJrT0,2017-04-21 06:47:32+00:00,2017,April,2017-11-14,Me-O Cats Commercial,Nobrand,98966,2486,184,532,False,False,False,22,People & Blogs
2,STI2fI7sKMo,2017-11-11 15:00:03+00:00,2017,November,2017-11-14,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,321053,4451,1772,895,False,False,False,22,People & Blogs

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  object
 1   publish_time            40949 non-null  object
 2   publish_year            40949 non-null  int32
 3   publish_month           40949 non-null  object
 4   trending_date           40949 non-null  datetime64[ns]
 5   title                   40949 non-null  object
 6   channel_title           40949 non-null  object
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  comments_disabled       40949 non-null  bool
 12  ratings_disabled        40949 non-null  bool
 13  video_error_or_removed  40949 non-null  bool
 14  category_id             40949 non-null  int64
 15  genre                   40949 non-null  object
dtypes: bool(3), datetime64[ns](1), int32(1), int64(5), object(6)
memory usage: 4.0+ MB

In [18]:
df['publish_time'] = df['publish_time'].astype(str)

In [20]:
#string slicing in dataframes
df['publish_time'] = df['publish_time'].str[:10]

In [72]:
df = pd.concat([publish_date,df],axis=1)

In [21]:
df = df.loc[:,['video_id','publish_time','publish_year', 'publish_month', 'trending_date', 'title', 'channel_title', 'views', 'likes', 'dislikes', 'comment_count',
       'comments_disabled', 'ratings_disabled', 'video_error_or_removed','category_id', 'genre']]

In [22]:
df

,video_id,publish_time,publish_year,publish_month,trending_date,title,channel_title,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,category_id,genre
0,2kyS6SvSYSE,2017-11-13,2017,November,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,748374,57527,2966,15954,False,False,False,22,People & Blogs
1,0mlNzVSJrT0,2017-04-21,2017,April,2017-11-14,Me-O Cats Commercial,Nobrand,98966,2486,184,532,False,False,False,22,People & Blogs
2,STI2fI7sKMo,2017-11-11,2017,November,2017-11-14,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,321053,4451,1772,895,False,False,False,22,People & Blogs
3,KODzih-pYlU,2017-11-11,2017,November,2017-11-14,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,Grace Helbig,197062,7250,217,456,False,False,False,22,People & Blogs
4,8mhTWqWlQzU,2017-11-11,2017,November,2017-11-14,Wearing Online Dollar Store Makeup For A Week,Safiya Nygaard,2744430,115426,1110,6541,False,False,False,22,People & Blogs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,V6ElE2xs48c,2018-05-10,2018,May,2018-06-02,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1324482,22413,608,1644,False,False,False,43,Shows
40945,V6ElE2xs48c,2018-05-10,2018,May,2018-06-03,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1332252,22461,610,1648,False,False,False,43,Shows
40946,V6ElE2xs48c,2018-05-10,2018,May,2018-06-04,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1340039,22504,615,1648,False,False,False,43,Shows
40947,V6ElE2xs48c,2018-05-10,2018,May,2018-06-05,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1345086,22542,615,1649,False,False,False,43,Shows
40948,V6ElE2xs48c,2018-05-10,2018,May,2018-06-06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1351321,22587,616,1649,False,False,False,43,Shows

In [17]:
df['genre'].unique()

array(['People & Blogs', 'Entertainment', 'Comedy',
       'Science & Technology', 'Film & Animation', 'News & Politics',
       'Sports', 'Music', 'Pets & Animals', 'Education', 'Howto & Style',
       'Autos & Vehicles', 'Travel & Events', 'Gaming',
       'Nonprofits & Activism', 'Shows'], dtype=object)

In [78]:
music = df.loc[(df['genre']=='Music')&(df['channel_title'].str.contains('childish',case=False))&(df['title'].str.contains('this is america',case=False)),['channel_title','title','genre','publish_month','publish_year','publish_time','trending_date','views']]

In [37]:
entertainment = df.loc[(df['genre']=='Entertainment')&(df['channel_title'].str.contains('the graham norton',case=False))&(df['title'].str.contains('jason momoa shows off',case=False)),['channel_title','title','genre','publish_month','publish_year','trending_date','views']]

In [47]:
nonprof = df.loc[(df['genre']=='Nonprofits & Activism')&(df['channel_title'].str.contains('logan paul vlogs',case=False))&(df['title'].str.contains('suicide:',case=False)),['channel_title','title','genre','publish_month','publish_year','trending_date','views']]

In [79]:
music.head()

,channel_title,title,genre,publish_month,publish_year,publish_time,trending_date,views
30920,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-08,31648454
30957,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-09,47169016
30998,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-10,60776509
31038,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-11,73432600
31084,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-12,85092067
31123,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-13,98938809
31192,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-15,116581406
31225,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-16,126191952
31261,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-17,134839555
31298,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-18,142421830
31332,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-19,149830680
31367,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-20,156612892
31406,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-21,162556776
31441,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-22,167997997
31479,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-23,173478072
31519,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-24,179045286
31560,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-25,184446490
31605,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-26,190950401
31647,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-27,196222618
31685,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-28,200820941
31725,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-29,205643016
31770,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-30,210338856
31813,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-31,217750076
31856,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-06-01,220490543
31902,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-06-02,225211923

In [80]:
entertainment

,channel_title,title,genre,publish_month,publish_year,trending_date,views
3256,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-15,391049
3310,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-16,574778
3368,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-17,647820
3420,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-18,694375
3473,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-19,732349
3529,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-20,766050
3581,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-21,792184

In [81]:
nonprof

,channel_title,title,genre,publish_month,publish_year,trending_date,views
40858,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-25,8041970
40859,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-26,15808339
40860,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-27,19092511
40861,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-28,21104436
40862,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-29,22387656
40863,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-30,23164093
40864,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-31,23742391
40865,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-02-01,24286474

In [26]:
df.loc[(df['genre']=='Music'),['video_id','channel_title','title','genre','publish_time','publish_month','publish_year','trending_date','views']]

,video_id,channel_title,title,genre,publish_time,publish_month,publish_year,trending_date,views
26038,5E4ZBSInqUU,marshmello,Marshmello - Blocks (Official Music Video),Music,2017-11-13,November,2017,2017-11-14,687582
26039,n1WpP7iowLc,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,Music,2017-11-10,November,2017,2017-11-14,17158531
26040,e_7zHm7GsYc,Hunter Hayes,Hunter Hayes - You Should Be Loved (Part One O...,Music,2017-11-13,November,2017,2017-11-14,13917
26041,zZ9FciUx6gs,Nickelback,Nickelback - The Betrayal Act III [Official Vi...,Music,2017-11-13,November,2017,2017-11-14,57169
26042,PaJCFHXcWmM,U2VEVO,U2 - The Blackout,Music,2017-11-13,November,2017,2017-11-14,60506
...,...,...,...,...,...,...,...,...,...
32505,2in8XqiElwc,NickiMinajAtVEVO,Nicki Minaj - Chun-Li (Live on SNL / 2018),Music,2018-05-20,May,2018,2018-06-14,4945185
32506,n_W54baizX8,Daddy Yankee,Daddy Yankee - Hielo (Video Oficial),Music,2018-05-18,May,2018,2018-06-14,41803845
32507,pcJo0tIWybY,SZAVEVO,SZA - Garden (Say It Like Dat) (Official Video),Music,2018-05-18,May,2018,2018-06-14,6004782
32508,7UoP9ABJXGE,Dan And Shay,Dan + Shay - Speechless (Wedding Video),Music,2018-05-18,May,2018,2018-06-14,5534278
32509,ju_inUnrLc4,FifthHarmonyVEVO,Fifth Harmony - Don't Say You Love Me,Music,2018-05-18,May,2018,2018-06-14,23502572

In [29]:
df['days_to_trend'] = (df['trending_date'] - df['publish_time']).dt.days

In [31]:
music_df = df[df['genre'] == 'Music']

In [32]:
first_5_days_df = music_df[music_df['days_to_trend'] <= 5]

In [46]:
first_5_days_views = first_5_days_df.groupby('video_id')['views'].mean()

In [47]:
first_5_days_views

video_id
-2aVkGcI7ZA     1668643.5
-35jibKqbEo     1082718.2
-5aaJJQFvOg      562232.0
-9rdDeWzvsU      296615.0
-BDImdAfodA      770754.5
                  ...
zi_6oaQyckM     4478349.8
zkG4Xpz6t68    14852405.2
zkrq7Kpd1so     1648886.0
zvjqcoiOPbE      672352.5
zwEn-ambXLw      127245.0
Name: views, Length: 765, dtype: float64